# Generated by Django 5.2.10 on 2026-03-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="branch",
        ),
    ]
