# Generated by Django 5.2.10 on 2026-03-07 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BranchManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manager_name", models.CharField(max_length=200)),
                (
                    "passport_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="franchise/passport_photos/"
                    ),
                ),
                ("id_proof_number", models.CharField(max_length=100)),
                ("institute_name", models.CharField(max_length=200)),
                ("trade_license_number", models.CharField(max_length=100)),
                ("institute_location", models.TextField()),
                (
                    "id_proof_file",
                    models.FileField(
                        blank=True, null=True, upload_to="franchise/id_proofs/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Franchise",
                "verbose_name_plural": "Franchises",
            },
        ),
        migrations.CreateModel(
            name="Franchise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manager_name", models.CharField(max_length=200)),
                ("institute_name", models.CharField(max_length=200)),
                ("institute_location", models.TextField()),
                (
                    "passport_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="franchise/passport/"
                    ),
                ),
                ("id_proof_number", models.CharField(max_length=100)),
                (
                    "id_proof_file",
                    models.FileField(
                        blank=True, null=True, upload_to="franchise/idproof/"
                    ),
                ),
                ("trade_license_number", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "franchise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="franchise.franchise",
                    ),
                ),
            ],
        ),
    ]
