# Generated by Django 5.2.10 on 2026-03-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="franchise",
            name="username",
            field=models.CharField(default="temp", max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
