# Generated by Django 5.2.10 on 2026-03-08 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0002_franchise_username"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="franchise",
            name="username",
        ),
        migrations.AddField(
            model_name="franchise",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="franchise",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
