# Generated by Django 5.2.10 on 2026-03-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0003_remove_franchise_username_franchise_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="franchise",
            name="user",
        ),
    ]
