# Generated by Django 5.2.10 on 2026-03-12 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0004_remove_franchise_user"),
        ("portal", "0002_remove_student_branch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="franchise",
        ),
        migrations.DeleteModel(
            name="BranchManager",
        ),
        migrations.AddField(
            model_name="franchise",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Branch",
        ),
    ]
