# Generated by Django 5.2.10 on 2026-03-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0005_remove_branch_franchise_delete_branchmanager_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="franchise",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
