# Generated by Django 5.2.10 on 2026-03-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0006_franchise_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="franchise",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="franchise",
            name="trade_license_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
