# Generated by Django 5.2.10 on 2026-03-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0007_franchise_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="franchise",
            name="force_password_change",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="franchise",
            name="reset_code",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="franchise",
            name="reset_code_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="franchise",
            name="reset_lock_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="franchise",
            name="reset_otp",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="franchise",
            name="reset_otp_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
