# Generated by Django 5.2.10 on 2026-03-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "franchise",
            "0008_franchise_force_password_change_franchise_reset_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="franchise",
            name="reset_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
