# Generated by Django 5.2.10 on 2026-03-14 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0009_franchise_reset_attempts"),
    ]

    operations = [
        migrations.CreateModel(
            name="FranchiseAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "franchise",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="franchise.franchise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Portal",
                "verbose_name_plural": "Access Portal",
            },
        ),
    ]
