# Generated by Django 5.2.10 on 2026-04-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0010_franchiseaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="franchise",
            name="is_restricted",
            field=models.BooleanField(default=False),
        ),
    ]
