# Generated by Django 5.2.10 on 2026-04-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0011_franchise_is_restricted"),
    ]

    operations = [
        migrations.AddField(
            model_name="franchise",
            name="signature",
            field=models.ImageField(
                blank=True, null=True, upload_to="franchise/signature/"
            ),
        ),
    ]
