# Generated by Django 5.2.10 on 2026-04-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0012_franchise_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="franchise",
            name="signature",
            field=models.ImageField(null=True, upload_to="franchise/signature/"),
        ),
    ]
