# Generated by Django 5.2.10 on 2026-05-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0013_alter_franchise_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="franchise",
            name="student_id_part1",
            field=models.CharField(default="MG", max_length=10),
        ),
        migrations.AddField(
            model_name="franchise",
            name="student_id_part2",
            field=models.CharField(default="SLG", max_length=10),
        ),
        migrations.AddField(
            model_name="franchise",
            name="student_id_part3",
            field=models.CharField(default="ms", max_length=10),
            preserve_default=False,
        ),
    ]
