# Generated by Django 5.2.10 on 2026-06-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website_portal", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebsiteCourse",
        ),
    ]
