# Generated by Django 5.2.10 on 2026-06-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("website_portal", "0002_delete_websitecourse"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Website Exam",
                "verbose_name_plural": "Website Exams",
            },
        ),
        migrations.CreateModel(
            name="WebsiteCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Duration in months"),
                ),
                ("admission_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("monthly_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("syllabus", models.TextField(blank=True)),
                (
                    "exams",
                    models.ManyToManyField(blank=True, to="website_portal.websiteexam"),
                ),
            ],
            options={
                "verbose_name": "Website Course",
                "verbose_name_plural": "Website Courses",
            },
        ),
    ]
