# Generated by Django 5.2.10 on 2026-06-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_portal", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="gallery/")),
            ],
            options={
                "verbose_name": "Gallery",
                "verbose_name_plural": "Gallery",
            },
        ),
    ]
