# Generated by Django 5.2.10 on 2026-06-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_portal", "0004_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
