# Generated by Django 5.2.10 on 2026-06-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_portal", "0005_gallery_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhyChooseUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField()),
            ],
            options={
                "verbose_name": "Why Choose Us",
                "verbose_name_plural": "Why Choose Us",
            },
        ),
    ]
