# Generated by Django 5.2.10 on 2026-06-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_portal", "0006_whychooseus"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitecourse",
            name="show_on_homepage",
            field=models.BooleanField(
                default=False, verbose_name="Show on Popular Courses"
            ),
        ),
    ]
