# Generated by Django 5.2.10 on 2026-06-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_portal", "0007_websitecourse_show_on_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitecourse",
            name="course_image",
            field=models.ImageField(null=True, upload_to="course_images/"),
        ),
    ]
