# Generated by Django 5.2.10 on 2026-06-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_portal", "0008_websitecourse_course_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        default="Smart Computer Institute", max_length=255
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Full physical address of the institute"
                    ),
                ),
                (
                    "phone_numbers",
                    models.TextField(
                        default="+91 XXXXX XXXXX, +91 YYYYY YYYYY",
                        help_text="Enter multiple phone numbers separated by commas",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        help_text="Official administrative email address",
                        max_length=254,
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        help_text="Active WhatsApp contact number", max_length=20
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Website Contact Information",
                "verbose_name_plural": "Website Contact Information",
            },
        ),
    ]
