# Generated by Django 5.2.10 on 2026-06-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_portal", "0009_websitecontact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="websitecontact",
            name="phone_numbers",
        ),
        migrations.RemoveField(
            model_name="websitecontact",
            name="whatsapp_number",
        ),
        migrations.AddField(
            model_name="websitecontact",
            name="phone_number_1",
            field=models.CharField(
                default="543534", max_length=20, verbose_name="Phone Number 1"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="websitecontact",
            name="phone_number_2",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone Number 2"
            ),
        ),
        migrations.AddField(
            model_name="websitecontact",
            name="phone_number_3",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone Number 3"
            ),
        ),
        migrations.AddField(
            model_name="websitecontact",
            name="whatsapp_number_1",
            field=models.CharField(
                default="432423$", max_length=20, verbose_name="WhatsApp Number 1"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="websitecontact",
            name="whatsapp_number_2",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="WhatsApp Number 2"
            ),
        ),
    ]
