# Generated by Django 5.2.10 on 2026-06-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_portal", "0010_remove_websitecontact_phone_numbers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitecontact",
            name="google_maps_link",
            field=models.URLField(
                blank=True,
                help_text="Paste the Google Maps share link here",
                max_length=500,
                null=True,
            ),
        ),
    ]
