# Generated by Django 5.2.10 on 2026-06-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_portal", "0011_websitecontact_google_maps_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websitecourse",
            name="course_image",
            field=models.ImageField(blank=True, null=True, upload_to="course_images/"),
        ),
    ]
