# Generated by Django 5.2.10 on 2026-06-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_portal", "0012_alter_websitecourse_course_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitecourse",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
