# Generated by Django 5.2.10 on 2026-06-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website_portal", "0013_websitecourse_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="websitecourse",
            options={
                "ordering": ["order"],
                "verbose_name": "Website Course",
                "verbose_name_plural": "Website Courses",
            },
        ),
    ]
