# Generated by Django 5.2.10 on 2026-06-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_portal", "0014_alter_websitecourse_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Example: 1000+, 98%, 10+", max_length=20
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Example: Students, Courses", max_length=100
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Website Statistic",
                "verbose_name_plural": "Website Statistics",
                "ordering": ["order"],
            },
        ),
    ]
