# Generated by Django 5.2.10 on 2026-06-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_portal", "0015_websitestat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="whychooseus",
            options={
                "ordering": ["order"],
                "verbose_name": "Why Choose Us",
                "verbose_name_plural": "Why Choose Us",
            },
        ),
        migrations.AddField(
            model_name="whychooseus",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
