# Generated by Django 5.2.10 on 2026-06-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_portal", "0016_alter_whychooseus_options_whychooseus_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("review", models.TextField()),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("course", models.CharField(blank=True, max_length=100)),
                (
                    "place",
                    models.CharField(
                        blank=True, help_text="Example: Google Review", max_length=100
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("show_on_homepage", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
