# Generated by Django 5.2.10 on 2026-06-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website_portal", "0017_testimonial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testimonial",
            options={"ordering": ["order"], "verbose_name": "Reviews"},
        ),
    ]
