# Generated by Django 5.2.10 on 2026-06-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_portal", "0019_alter_testimonial_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={
                "ordering": ["order"],
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery",
            },
        ),
        migrations.AddField(
            model_name="gallery",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
