# Generated by Django 5.2.10 on 2026-03-17 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_portal", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notice",
            old_name="sent",
            new_name="is_sent",
        ),
        migrations.RemoveField(
            model_name="notice",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="notice",
            name="schedule_time",
        ),
        migrations.AddField(
            model_name="notice",
            name="scheduled_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
