# Generated by Django 5.2.10 on 2026-03-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management_portal",
            "0002_rename_sent_notice_is_sent_remove_notice_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="scheduled_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
