# Generated by Django 5.2.10 on 2026-03-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_portal", "0003_alter_notice_scheduled_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
