# Generated by Django 5.2.10 on 2026-03-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_portal", "0004_notice_sent_at"),
        ("student_portal", "0009_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="students",
            field=models.ManyToManyField(
                blank=True, to="student_portal.studentadmission"
            ),
        ),
    ]
