# Generated by Django 5.2.10 on 2026-03-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_portal", "0005_notice_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="sender_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
