# Generated by Django 5.2.10 on 2026-03-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_portal", "0006_notice_sender_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAdmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("course_completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name="notice",
            options={"ordering": ["-scheduled_time", "-sent_at"]},
        ),
        migrations.AlterField(
            model_name="notice",
            name="sender_id",
            field=models.CharField(
                blank=True,
                default="Smart Computer Institute",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="students",
            field=models.ManyToManyField(
                blank=True, to="management_portal.studentadmission"
            ),
        ),
    ]
