# Generated by Django 5.2.10 on 2026-03-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_portal", "0007_studentadmission_alter_notice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentadmission",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
