# Generated by Django 5.2.10 on 2026-03-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_portal", "0008_studentadmission_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notice",
            options={
                "ordering": ["-scheduled_time", "-sent_at"],
                "verbose_name": "Notice",
                "verbose_name_plural": "Notices",
            },
        ),
        migrations.AlterField(
            model_name="notice",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="notices",
                to="management_portal.studentadmission",
            ),
        ),
        migrations.AlterField(
            model_name="studentadmission",
            name="student_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
