# Generated by Django 5.2.10 on 2026-04-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management_portal",
            "0009_alter_notice_options_alter_notice_students_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="progress",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
