# Generated by Django 5.2.10 on 2026-04-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management_portal", "0010_notice_progress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notice",
            options={"ordering": ["-id"]},
        ),
    ]
