# Generated by Django 5.2.10 on 2026-05-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management_portal", "0011_alter_notice_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notice",
            options={
                "ordering": ["-scheduled_time", "-sent_at"],
                "verbose_name": "Notice",
                "verbose_name_plural": "Notices",
            },
        ),
    ]
