# Generated by Django 5.2.10 on 2026-05-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management_portal", "0013_notice_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notice",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Notice",
                "verbose_name_plural": "Notices",
            },
        ),
    ]
