# Generated by Django 5.2.10 on 2026-05-22 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_portal", "0015_notice_franchise"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticeHidden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("franchise_user", models.CharField(max_length=100)),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_portal.notice",
                    ),
                ),
            ],
        ),
    ]
