# Generated by Django 5.2.10 on 2026-05-23 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0014_franchise_student_id_part1_and_more"),
        ("management_portal", "0017_exam_studentmarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmarks",
            name="franchise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="franchise.franchise",
            ),
        ),
    ]
