# Generated by Django 5.2.10 on 2026-05-23 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_portal", "0018_studentmarks_franchise"),
        ("student_portal", "0037_alter_notice_franchise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmarks",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="student_portal.studentadmission",
            ),
        ),
    ]
