# Generated by Django 5.2.10 on 2026-05-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_portal", "0019_alter_studentmarks_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmarks",
            name="marks",
            field=models.IntegerField(verbose_name="Marks Obtained"),
        ),
    ]
