# Generated by Django 5.2.10 on 2026-06-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management_portal", "0020_alter_studentmarks_marks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentmarks",
            options={
                "verbose_name": "Student mark",
                "verbose_name_plural": "Student marks",
            },
        ),
    ]
