# Generated by Django 5.2.10 on 2026-03-08 09:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BatchDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Class day",
                "verbose_name_plural": "Class days",
            },
        ),
        migrations.CreateModel(
            name="BatchTiming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Class timing",
                "verbose_name_plural": "Class timings",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("admission_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "monthly_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("duration", models.IntegerField(help_text="Duration in months")),
                ("total_fees", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="StudentAdmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "passport_photo",
                    models.ImageField(null=True, upload_to="passport_photos/"),
                ),
                ("guardian_name", models.CharField(max_length=100, null=True)),
                ("dob", models.DateField(null=True)),
                ("phone", models.CharField(max_length=10)),
                ("qualification", models.CharField(max_length=100, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "last_qualification_file",
                    models.FileField(null=True, upload_to="last_qualification/"),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[("AADHAAR", "Aadhaar"), ("OTHER", "Other")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("document_number", models.CharField(max_length=30, null=True)),
                ("document_file", models.FileField(null=True, upload_to="documents/")),
                ("address", models.TextField(null=True)),
                (
                    "course_type",
                    models.CharField(
                        choices=[("TYPE 1", "Type 1"), ("TYPE 2", "Type 2")],
                        default="TYPE 1",
                        max_length=10,
                    ),
                ),
                ("course_duration", models.IntegerField(null=True)),
                (
                    "monthly_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("admission_date", models.DateField(null=True)),
                ("receipt_no", models.CharField(max_length=50, null=True)),
                (
                    "admission_pay_via",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CASH", "Cash"),
                            ("ONLINE", "Online"),
                            ("CARD", "Card"),
                        ],
                        default="CASH",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "admission_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "advance_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "final_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "class_day",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="student_portal.batchday",
                    ),
                ),
                (
                    "class_time",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="student_portal.batchtiming",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="student_portal.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[("TYPE 1", "Type 1"), ("TYPE 2", "Type 2")],
                        default="TYPE 1",
                        max_length=10,
                    ),
                ),
                ("course_duration", models.IntegerField(blank=True, null=True)),
                (
                    "monthly_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "class_day",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="student_portal.batchday",
                    ),
                ),
                (
                    "class_time",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="student_portal.batchtiming",
                    ),
                ),
                (
                    "new_course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_upgrades",
                        to="student_portal.course",
                    ),
                ),
                (
                    "old_course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="old_upgrades",
                        to="student_portal.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="student_portal.studentadmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_date", models.DateField()),
                ("total_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("monthly_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration", models.IntegerField()),
                ("admission_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_portal.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="student_portal.studentadmission",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "course")},
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("certificate_no", models.CharField(max_length=50)),
                ("certificate_file", models.FileField(upload_to="certificates/")),
                ("marksheet_no", models.CharField(max_length=50)),
                ("marksheet_file", models.FileField(upload_to="marksheets/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="student_portal.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_portal.studentadmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BatchListView",
            fields=[],
            options={
                "verbose_name": "Batch List",
                "verbose_name_plural": "Batch Lists",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("student_portal.studentadmission",),
        ),
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[],
            options={
                "verbose_name": "Payment History",
                "verbose_name_plural": "Payment Histories",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("student_portal.studentadmission",),
        ),
        migrations.CreateModel(
            name="Fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("receipt_no", models.CharField(max_length=50, unique=True)),
                (
                    "pay_via",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("ONLINE", "Online")],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "fine",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[("ADMISSION", "Admission"), ("MONTHLY", "Monthly")],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="student_portal.courseenrollment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["enrollment"], name="student_por_enrollm_60684d_idx"
                    ),
                    models.Index(
                        fields=["receipt_no"], name="student_por_receipt_e71543_idx"
                    ),
                ],
            },
        ),
    ]
