# Generated by Django 5.2.10 on 2026-03-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentadmission",
            name="class_day",
        ),
        migrations.AddField(
            model_name="studentadmission",
            name="class_day",
            field=models.ManyToManyField(to="student_portal.batchday"),
        ),
    ]
