# Generated by Django 5.2.10 on 2026-03-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0003_batchday_created_at_batchday_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchday",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="batchday",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="batchday",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="batchtiming",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="batchtiming",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="batchtiming",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="course",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="course",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="course",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="courseupgrade",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="courseupgrade",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="courseupgrade",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="fee",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="fee",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="fee",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="studentadmission",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="studentadmission",
            name="updated_at",
        ),
    ]
