# Generated by Django 5.2.10 on 2026-03-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_portal",
            "0004_remove_batchday_created_at_remove_batchday_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="studentadmission",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Student email for payment reminders",
                max_length=254,
                null=True,
            ),
        ),
    ]
