# Generated by Django 5.2.10 on 2026-03-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0005_studentadmission_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_run", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
