# Generated by Django 5.2.10 on 2026-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0007_studentadmission_leave_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentadmission",
            name="leave_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
