# Generated by Django 5.2.10 on 2026-03-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0008_studentadmission_leave_start"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("scheduled_time", models.DateTimeField()),
                ("is_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
