# Generated by Django 5.2.10 on 2026-03-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0010_notice_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="notices", to="student_portal.studentadmission"
            ),
        ),
    ]
