# Generated by Django 5.2.10 on 2026-03-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0011_alter_notice_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentadmission",
            name="course_completed",
            field=models.BooleanField(default=False),
        ),
    ]
