# Generated by Django 5.2.10 on 2026-04-07 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0012_studentadmission_course_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="receipt_no",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Receipt number must contain only digits (0-9).",
                        regex="^\\d+$",
                    )
                ],
            ),
        ),
    ]
