# Generated by Django 5.2.10 on 2026-04-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0013_alter_fee_receipt_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="waive_fine",
            field=models.BooleanField(default=False),
        ),
    ]
