# Generated by Django 5.2.10 on 2026-04-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0014_fee_waive_fine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="marksheet_file",
            field=models.FileField(blank=True, null=True, upload_to="marksheets/"),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="marksheet_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
