# Generated by Django 5.2.10 on 2026-04-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0015_alter_certificate_marksheet_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="certificate_prefix",
            field=models.CharField(default="SCI/SLG/", max_length=20),
        ),
    ]
