# Generated by Django 5.2.10 on 2026-04-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0016_certificate_certificate_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certificate_prefix",
            field=models.CharField(default="SCI/2026/", max_length=20),
        ),
    ]
