# Generated by Django 5.2.10 on 2026-04-22 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0011_franchise_is_restricted"),
        ("student_portal", "0017_alter_certificate_certificate_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchday",
            name="franchise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="franchise.franchise",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="batchtiming",
            name="franchise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="franchise.franchise",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="certificate",
            name="franchise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="franchise.franchise",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="franchise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="franchise.franchise",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="franchise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="franchise.franchise",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courseupgrade",
            name="franchise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="franchise.franchise",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fee",
            name="franchise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="franchise.franchise",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notice",
            name="franchise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="franchise.franchise",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentadmission",
            name="franchise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="franchise.franchise",
            ),
            preserve_default=False,
        ),
    ]
