# Generated by Django 5.2.10 on 2026-04-24 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0011_franchise_is_restricted"),
        ("student_portal", "0018_batchday_franchise_batchtiming_franchise_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchday",
            name="franchise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="franchise.franchise",
            ),
        ),
        migrations.AlterField(
            model_name="batchtiming",
            name="franchise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="franchise.franchise",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="franchise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="franchise.franchise",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="franchise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="franchise.franchise",
            ),
        ),
        migrations.AlterField(
            model_name="courseenrollment",
            name="franchise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="franchise.franchise",
            ),
        ),
        migrations.AlterField(
            model_name="courseupgrade",
            name="franchise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="franchise.franchise",
            ),
        ),
        migrations.AlterField(
            model_name="fee",
            name="franchise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="franchise.franchise",
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="franchise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="franchise.franchise",
            ),
        ),
        migrations.AlterField(
            model_name="studentadmission",
            name="franchise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="franchise.franchise",
            ),
        ),
    ]
