# Generated by Django 5.2.10 on 2026-04-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_portal",
            "0022_alter_batchday_franchise_alter_batchtiming_franchise_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstudentadmission",
            name="is_suspended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalstudentadmission",
            name="suspension_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="studentadmission",
            name="is_suspended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentadmission",
            name="suspension_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
