# Generated by Django 5.2.10 on 2026-04-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0023_historicalstudentadmission_is_suspended_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstudentadmission",
            name="suspension_reason",
        ),
        migrations.RemoveField(
            model_name="studentadmission",
            name="suspension_reason",
        ),
    ]
