# Generated by Django 5.2.10 on 2026-04-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_portal",
            "0024_remove_historicalstudentadmission_suspension_reason_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstudentadmission",
            name="is_freezed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentadmission",
            name="is_freezed",
            field=models.BooleanField(default=False),
        ),
    ]
