# Generated by Django 5.2.10 on 2026-05-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0025_historicalstudentadmission_is_freezed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="email_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcertificate",
            name="email_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertificate",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
