# Generated by Django 5.2.10 on 2026-05-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_portal",
            "0026_certificate_email_error_certificate_email_sent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertificate",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
