# Generated by Django 5.2.10 on 2026-05-04 10:36

import student_portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0027_certificate_published_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuedCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        upload_to="certificates/",
                        validators=[student_portal.models.validate_file_size],
                    ),
                ),
                (
                    "marksheet_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="marksheets/",
                        validators=[student_portal.models.validate_file_size],
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="certificate",
            name="certificate_file",
            field=models.FileField(
                upload_to="certificates/",
                validators=[student_portal.models.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="marksheet_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="marksheets/",
                validators=[student_portal.models.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="historicalcertificate",
            name="certificate_file",
            field=models.TextField(
                max_length=100, validators=[student_portal.models.validate_file_size]
            ),
        ),
        migrations.AlterField(
            model_name="historicalcertificate",
            name="marksheet_file",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[student_portal.models.validate_file_size],
            ),
        ),
    ]
