# Generated by Django 5.2.10 on 2026-08-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_portal",
            "0028_issuedcertificate_alter_certificate_certificate_file_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="fee",
            name="remaining_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalfee",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalfee",
            name="remaining_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
