# Generated by Django 5.2.10 on 2026-08-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0029_fee_paid_amount_fee_remaining_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fee",
            old_name="remaining_amount",
            new_name="remaining_fee",
        ),
        migrations.RenameField(
            model_name="historicalfee",
            old_name="remaining_amount",
            new_name="remaining_fee",
        ),
        migrations.AddField(
            model_name="fee",
            name="remaining_fine",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalfee",
            name="remaining_fine",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
