# Generated by Django 5.2.10 on 2026-08-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0030_rename_remaining_amount_fee_remaining_fee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fee",
            name="paid_amount",
        ),
        migrations.RemoveField(
            model_name="fee",
            name="remaining_fee",
        ),
        migrations.RemoveField(
            model_name="fee",
            name="remaining_fine",
        ),
        migrations.RemoveField(
            model_name="historicalfee",
            name="paid_amount",
        ),
        migrations.RemoveField(
            model_name="historicalfee",
            name="remaining_fee",
        ),
        migrations.RemoveField(
            model_name="historicalfee",
            name="remaining_fine",
        ),
    ]
