# Generated by Django 5.2.10 on 2026-08-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_portal",
            "0031_remove_fee_paid_amount_remove_fee_remaining_fee_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="remaining_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="fee",
            name="remaining_fine",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalfee",
            name="remaining_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalfee",
            name="remaining_fine",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
