# Generated by Django 5.2.10 on 2026-08-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0032_fee_remaining_fee_fee_remaining_fine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="generated_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalfee",
            name="generated_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
