# Generated by Django 5.2.10 on 2026-08-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0034_fee_generated_fine_historicalfee_generated_fine"),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="generated_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalfee",
            name="generated_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
