# Generated by Django 5.2.10 on 2026-05-22 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0014_franchise_student_id_part1_and_more"),
        ("student_portal", "0035_fee_generated_total_historicalfee_generated_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="franchise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="franchise.franchise",
            ),
        ),
    ]
