# Generated by Django 5.2.10 on 2026-05-22 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0014_franchise_student_id_part1_and_more"),
        ("student_portal", "0036_alter_notice_franchise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="franchise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="franchise.franchise",
            ),
        ),
    ]
