# Generated by Django 5.2.10 on 2026-06-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0037_alter_notice_franchise"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcertificate",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
