# Generated by Django 5.2.10 on 2026-06-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_portal", "0022_lead"),
        ("student_portal", "0038_certificate_end_date_historicalcertificate_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="exams",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="management_portal.exam"
            ),
        ),
    ]
