# Generated by Django 5.2.10 on 2026-06-30 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0039_course_exams"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="exams",
        ),
    ]
