# Generated by Django 5.2.10 on 2026-08-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0040_remove_course_exams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="fee_type",
            field=models.CharField(
                choices=[
                    ("ADMISSION", "Admission"),
                    ("MONTHLY", "Monthly"),
                    ("ADVANCE", "Advance"),
                ],
                default="MONTHLY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfee",
            name="fee_type",
            field=models.CharField(
                choices=[
                    ("ADMISSION", "Admission"),
                    ("MONTHLY", "Monthly"),
                    ("ADVANCE", "Advance"),
                ],
                default="MONTHLY",
                max_length=20,
            ),
        ),
    ]
