# Generated by Django 5.2.10 on 2026-08-22 05:55

import student_portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0041_alter_fee_fee_type_alter_historicalfee_fee_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certificate_file",
            field=models.FileField(
                upload_to="certificates/",
                validators=[
                    student_portal.models.validate_file_size,
                    student_portal.models.validate_pdf_file,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="marksheet_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="marksheets/",
                validators=[
                    student_portal.models.validate_file_size,
                    student_portal.models.validate_pdf_file,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalcertificate",
            name="certificate_file",
            field=models.TextField(
                max_length=100,
                validators=[
                    student_portal.models.validate_file_size,
                    student_portal.models.validate_pdf_file,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalcertificate",
            name="marksheet_file",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    student_portal.models.validate_file_size,
                    student_portal.models.validate_pdf_file,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalstudentadmission",
            name="passport_photo",
            field=models.TextField(
                max_length=100,
                null=True,
                validators=[student_portal.models.validate_passport_photo_size],
            ),
        ),
        migrations.AlterField(
            model_name="issuedcertificate",
            name="certificate_file",
            field=models.FileField(
                upload_to="certificates/",
                validators=[
                    student_portal.models.validate_file_size,
                    student_portal.models.validate_pdf_file,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="issuedcertificate",
            name="marksheet_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="marksheets/",
                validators=[
                    student_portal.models.validate_file_size,
                    student_portal.models.validate_pdf_file,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentadmission",
            name="passport_photo",
            field=models.ImageField(
                null=True,
                upload_to="passport_photos/",
                validators=[student_portal.models.validate_passport_photo_size],
            ),
        ),
    ]
