# Generated by Django 5.2.10 on 2026-08-22 06:15

import cloudinary_storage.storage
import student_portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0042_alter_certificate_certificate_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certificate_file",
            field=models.FileField(
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="certificates/",
                validators=[
                    student_portal.models.validate_file_size,
                    student_portal.models.validate_pdf_file,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="marksheet_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="marksheets/",
                validators=[
                    student_portal.models.validate_file_size,
                    student_portal.models.validate_pdf_file,
                ],
            ),
        ),
    ]
