name: Django Scheduler

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  scheduler:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check DATABASE_URL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python -c "import os; from urllib.parse import urlparse; u=os.environ.get('DATABASE_URL',''); print('DATABASE_URL exists:', bool(u)); print('Starts with:', u[:20]); print('Scheme:', urlparse(u).scheme)"

      - name: Run scheduler
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: "False"
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}

          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

        run: python manage.py run_scheduler